<it4all-files-exercise
  [exerciseFiles]="exerciseFiles"
  [isCorrecting]="isCorrecting"
  [sampleSolutions]="sampleSolutions"
  (correct)="correct()"
  defaultMode="python">
  <ng-container exText>
    <span [innerHTML]="exerciseFragment.text"></span>
  </ng-container>
  <ng-container correctionContent>

    <div class="message is-danger" *ngIf="queryError">
      <div class="message-header">Es gab einen internen Fehler bei der Korrektur:</div>
      <div class="message-body">
        <pre>{{queryError.message}}</pre>
      </div>
    </div>

    <ng-container *ngIf="correctionResult">

      <div class="my-3">
        <it4all-solution-saved [solutionSaved]="correctionResult.solutionSaved"></it4all-solution-saved>
      </div>

      <div class="my-3">
        <it4all-points-notification [points]="abstractResult.points" [maxPoints]="abstractResult.maxPoints">
        </it4all-points-notification>
      </div>

      <div class="content my-3" *ngIf="unitTestResults && unitTestResults.length > 0">
        <ul *ngFor="let unitTestResult of unitTestResults">
          <it4all-programming-unit-test-result [unitTestResult]="unitTestResult">
          </it4all-programming-unit-test-result>
        </ul>
      </div>

      <it4all-programming-normal-result *ngIf="implementationCorrectionResult"
                                        [normalResult]="implementationCorrectionResult">
      </it4all-programming-normal-result>
    </ng-container>
  </ng-container>
</it4all-files-exercise>
